---
title: "roadmap"
author: "Ajay, Esben and Simon"
date: "21/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Gamma version (7/11)
- A class that contain parameters for the HMM , Simon
-new print functions , Simon
- EM , Esben 
- Forward, Backward , Esben 
- Decode , Esben
- State prediction , Simon
- Forecasting , Simon
- new plot functions
- Generating data from HMM
- Find Data , Ajay

## Beta version (15/11)
- Write vignette to showcase use of package 
- Test functions and add warnings  

## Finish version

Priority 1:
- Add into to vignette

- Deal with underflow # Simon - Done

- Add stationary option / deal with problem in the vignette - Done

- add more distributions to EM # Simon 

- explain parameters in HMM class better + simplify the parameter # Simon

- add tidyverse/tibble to documentation.  

- add warning to HMM and other functions # Esben - Done

Priority 2:

- consider add more functionality to HMM class. Consider adding option for it to run the EM algo if the user supply data. 

- Standardizing of Parameters.

- add background to vignette # Esben - Done

- replace $ with * in vignette - Done

Priority 3:
- optimize code (look at viterbi)
