---
title: "use_of_plot_lurk_residuals"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{use_of_plot_lurk_residuals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


\section{Background}

A common practice in statistic when given data, is to see if there is correlation between the different variables.
However when we do this we need to be careful that we do not read to much into the correlation.
Because while a high correlation between two variable may speak to a relationship between the two,
it could also be a "fake" relationship. One possible cause of this could be a lurking variable. 
A lurking variable is a variable that is dependent on by both the variable we are looking at. Which the creates
a illusion of high correlation. 


A example could be ice cream sale and heatstroke on some beach. It is not hard to see that 
both variable would be big on the days where it is hot and low when it is cold. In this case
it is clear that we have temperature as a lurking variable. However if we did not consider this
then we could have thought that eating ice cream could course heatstroke. 


The function plot_lurk_residuals will allow us to see if our data has $Z$ as a lurking variable. It does by plotting the residulas of the 
linear model of $X$ on $Z$ against the residuals of the linear model  $Y$ on $Z$.

\section{Practise}
